### ISSUE TITLE
[Bug]: Missing API username and password in icingadb transport

### ISSUE THREAD

**Issue by MTSym** [Icinga/helm-charts#19]
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.1.0

### Please describe your problem

By creating the stack and only setting the required passwords the `command transport` entry in `icingadb` is created without a valid username and password. Because of that when trying to use `check now` at a service etc. you will get an 401 unauthorized error.

When setting the API values to `director` and the corresponding password everything seems to work again.

**Comment by mocdaniel** [comment]
This is definitely a bug, we'll get it fixed asap.

**Comment by mocdaniel** [comment]
That’s right. I’ll go ahead and close this issue. The fix will be in v0.2.0 which we plan to release soon.
