### ISSUE TITLE
[Feature]: Add configurable secret references for sensible values

### ISSUE THREAD

**Issue by mocdaniel** [Icinga/helm-charts#2]
### Affected Chart

icinga-stack

### Please describe your feature request

Right now, sensible values such as ticket salt, API credentials, or database credentials, can only be passed as plain text in `values.yaml`.

We should support referencing secrets instead if possible, as many Helm charts do. **IcingaDB** and **Icingaweb2** are fully configurable via environment variables, so we could just reference said secret entries there.

For **Icinga2**, config needs to be generated, which makes working with secret references a bit more tedious. We could try to inject the secrets to the precreated configuration files using another `init` container, I guess.

**Comment by julianbrost** [comment]
> We could try to inject the secrets to the precreated configuration files

You can simply do something like `const TicketSalt = getenv("ICINGA2_TICKET_SALT")` in there.

**Comment by CanisLupusLupus** [comment]
I'm interested in implementing this feature. I'm just wondering if anyone is already working on it so I won't duplicate the effort?

**Comment by mocdaniel** [comment]
Hey, that'd be much appreciated, thanks a lot! To my knowledge, nobody is actively working on this feature, unless @Donien has started some experiments?

**Comment by Donien** [comment]
I had been working on this for a bit but didn't have time to actually finish anything of significance. I also don't currently plan on continuing the effort, at least not in the near future.  

As far as I'm concerned, yes, @CanisLupusLupus , feel free and go ahead if you want to contribute :)

Nonetheless, I'll leave a link to [what I'd been doing](https://github.com/Icinga/helm-charts/compare/main...Donien:helm-charts:feature/configurable-secrets) if anyone needs some inspiration. 

Concerning the CLI command my idea was to basically use either

```
...
--set icinga2.config.ticket_salt.value=CHANGE-ME \
...
```

or

```
...
--set icinga2.config.ticket_salt.secret.name=CHANGE-ME \
--set icinga2.config.ticket_salt.secret.key=CHANGE-ME \
...
```

depending on whether you want to directly set a value or use a Kubernetes secret (keeping a relatively clear structure).  
This, however, is just a suggestion :)

**Comment by mocdaniel** [comment]
Thanks for the update!

@CanisLupusLupus, I will go ahead and assign you to the issue then. Feel free to use this issue for questions, communication, or guidance.

**Comment by CanisLupusLupus** [comment]
My initial idea was to only use secrets for configuration  of sensible values, but I really like the flexibility of @Donien's idea. I would modify it to also set username from secret.

So, for example, to set Icingaweb2 database credentials we would use:
- without secret:
```
...
-- set global.databases.icingaweb2.username.value=CHANGE-ME \
-- set global.databases.icingaweb2.password.value=CHANGE-ME \
...
```
- with secret:
```
...
-- set global.databases.icingaweb2.secretName=CHANGE-ME \
-- set global.databases.icingaweb2.username.secretKey=CHANGE-ME \
-- set global.databases.icingaweb2.password.secretKey=CHANGE-ME \
...
```
I am of course open to suggestions.

**Comment by mocdaniel** [comment]
That's exactly what I'd be looking for and how many popular charts handle secret management. Feel free to go ahead and draft a first PR :)
