### ISSUE TITLE
[Bug]: is livestatus Features is deprecated in Icinga2 helmchart

### ISSUE THREAD

**Issue by Vikraam27** [Icinga/helm-charts#33]
### Affected Chart

icinga2

### Which version of the app contains the bug?

2.13.7

### Please describe your problem

i want ask in documentation icinga2 helmchart there is no features livestatus, is that deprecated or not?
because i always got an error when i put this livestatus.conf and i put in folder /etc/icinga2/features-enabled mounted as configmaps, this my code
`object LivestatusListener "livestatus" { }

library "livestatus"

object LivestatusListener "livestatus-tcp" {
  socket_type = "tcp"
  bind_host = "0.0.0.0"
  bind_port = "6558"
}`

and this is error from icinga2 pods
<img width="1063" alt="image" src="https://github.com/Icinga/helm-charts/assets/49831979/9cdca9c5-2f61-46c8-8cd6-17cfd9b32e54">

, if this features is deprecated, how do i connect icinga2 to thruk?

**Comment by martialblog** [comment]
The Livestatus feature has been deprecated since Icinga2 2.12

https://raw.githubusercontent.com/Icinga/icinga2/master/CHANGELOG.md
