### ISSUE TITLE
[Bug]: Icinga kubernetes pod goes into CrashLoopBackOff at installation

### ISSUE THREAD

**Issue by bosseedi** [Icinga/helm-charts#61]
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.3.0

### Please describe your problem

Hi, I can not install the chart, the icinga-kubernetes pod goes into a CrashLoopBackOff. In the logs I can see this error:

I0917 10:43:35.582852       1 database.go:286] "Connecting to database" logger="database"
F0917 10:43:36.227691       1 main.go:313] can't retry: can't perform "INSERT INTO `service` (`cluster_ips`, `external_ips`, `ip_family_policy`, `uid`, `created`, `cluster_ip`, `session_affinity`, `uuid`, `name`, `type`, `publish_not_ready_addresses`, `health_check_node_port`, `load_balancer_class`, `internal_traffic_policy`, `external_traffic_policy`, `ip_families`, `resource_version`, `external_name`, `yaml`, `namespace`, `allocate_load_balancer_node_ports`) VALUES (:cluster_ips, :external_ips, :ip_family_policy, :uid, :created, :cluster_ip, :session_affinity, :uuid, :name, :type, :publish_not_ready_addresses, :health_check_node_port, :load_balancer_class, :internal_traffic_policy, :external_traffic_policy, :ip_families, :resource_version, :external_name, :yaml, :namespace, :allocate_load_balancer_node_ports) ON DUPLICATE KEY UPDATE `cluster_ips` = VALUES(`cluster_ips`), `external_ips` = VALUES(`external_ips`), `ip_family_policy` = VALUES(`ip_family_policy`), `uid` = VALUES(`uid`), `created` = VALUES(`created`), `cluster_ip` = VALUES(`cluster_ip`), `session_affinity` = VALUES(`session_affinity`), `uuid` = VALUES(`uuid`), `name` = VALUES(`name`), `type` = VALUES(`type`), `publish_not_ready_addresses` = VALUES(`publish_not_ready_addresses`), `health_check_node_port` = VALUES(`health_check_node_port`), `load_balancer_class` = VALUES(`load_balancer_class`), `internal_traffic_policy` = VALUES(`internal_traffic_policy`), `external_traffic_policy` = VALUES(`external_traffic_policy`), `ip_families` = VALUES(`ip_families`), `resource_version` = VALUES(`resource_version`), `external_name` = VALUES(`external_name`), `yaml` = VALUES(`yaml`), `namespace` = VALUES(`namespace`), `allocate_load_balancer_node_ports` = VALUES(`allocate_load_balancer_node_ports`)": Error 1265 (01000): Data truncated for column 'type' at row 79

**Comment by lippserd** [comment]
Hi @bosseedi,

Thanks for the report. There was a typo in the schema introduced just recently which has been fixed. Please pull the `icinga-kubernetes` image and try again. You have to drop and recreate the kubernetes database beforehand though. Or just recreate the whole deployment.

Best regards,
Eric

**Comment by bosseedi** [comment]
thanks that fixed the issue
